# Generated by Django 6.0.1 on 2026-02-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_department_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='semester',
        ),
    ]
